---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kindnet-controller
rules:
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - get
      - create
      - update
  - apiGroups:
      - apps
    resources:
      - daemonsets
    verbs:
      - get
      - create
      - update
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - create
      - update
  - apiGroups:
      - "kindnet.io"
    resources:
      - configurations
    verbs:
      - list
      - watch
      - get
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kindnet-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kindnet-controller
subjects:
  - kind: ServiceAccount
    name: kindnet-controller
    namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kindnet-controller
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kindnet-controller
  namespace: kube-system
  labels:
    app: kindnet-controller
    k8s-app: kindnet-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kindnet-controller
  template:
    metadata:
      labels:
        app: kindnet-controller
        k8s-app: kindnet-controller
    spec:
      tolerations:
        - operator: Exists
          effect: NoSchedule
      serviceAccountName: kindnet-controller
      containers:
        - name: kindnet-controller
          image: ghcr.io/aojea/kindnet-controller:v1.1.0
          resources:
            requests:
              cpu: "100m"
              memory: "50Mi"
            limits:
              cpu: "100m"
              memory: "50Mi"
---

