{
 "title": "Kindnet",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Connection bytes sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kindnet_conntrack_connection_bytes_total_sum{protocol=\"tcp\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kindnet_conntrack_connection_bytes_total_sum{protocol=\"udp\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connection packets sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "kindnet_conntrack_connection_packets_total_sum{protocol=\"tcp\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kindnet_conntrack_connection_packets_total_sum{protocol=\"udp\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connection duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(kindnet_conntrack_connection_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top talkers by connection bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "topk(10, sum by(src_ip) (rate(kindnet_conntrack_connection_bytes_total_sum[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Packet drop",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(kindnet_conntrack_stats_early_drop_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connection errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(kindnet_conntrack_stats_error_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TCP connection latency",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kindnet_conntrack_tcp_connection_seen_reply_latency_milliseconds_sum)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}