---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kindnetd
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - services
    verbs:
      - list
      - watch
      - patch
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
  - apiGroups:
      - "kindnet.io"
    resources:
      - configurations
    verbs:
      - list
      - watch
      - get
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kindnetd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kindnetd
subjects:
  - kind: ServiceAccount
    name: kindnetd
    namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kindnetd
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kindnetd
  namespace: kube-system
  labels:
    tier: node
    app: kindnetd
    k8s-app: kindnetd
spec:
  selector:
    matchLabels:
      app: kindnetd
  template:
    metadata:
      labels:
        tier: node
        app: kindnetd
        k8s-app: kindnetd
    spec:
      hostNetwork: true
      tolerations:
        - operator: Exists
          effect: NoSchedule
      serviceAccountName: kindnetd
      initContainers:
        - name: install-cni-bin
          image: ghcr.io/aojea/kindnetd:v1.1.0
          command:
            [
              "sh",
              "-c",
              "cd /opt/cni/bin; for i in * ; do cat $i > /cni/$i ; chmod +x /cni/$i ; done",
            ]
          volumeMounts:
            - name: cni-bin
              mountPath: /cni
      containers:
        - name: kindnetd-cni
          image: ghcr.io/aojea/kindnetd:v1.1.0
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - name: cni-cfg
              mountPath: /etc/cni/net.d
            - name: lib-modules
              mountPath: /lib/modules
              readOnly: true
          resources:
            requests:
              cpu: "100m"
              memory: "50Mi"
            limits:
              cpu: "100m"
              memory: "50Mi"
          securityContext:
            privileged: false
            capabilities:
              add: ["NET_RAW", "NET_ADMIN"]
      volumes:
        - name: cni-bin
          hostPath:
            path: /opt/cni/bin
            type: DirectoryOrCreate
        - name: cni-cfg
          hostPath:
            path: /etc/cni/net.d
            type: DirectoryOrCreate
        - name: lib-modules
          hostPath:
            path: /lib/modules
---

