baseURL = 'https://kindnet.es/'
languageCode = 'en-us'
title = 'Kindnet'

# we use this to disable indexing for the non-production build
enableRobotsTXT = true

contentDir = "content"

# syntax highlighting options
[markup]
[markup.highlight]
codeFences = true
hl_Lines = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "vs"
tabWidth = 4

# allow html in markdown
[markup.goldmark.renderer]
unsafe = true

# enable hugo's menu system for the site, name the primary menu
sectionPagesMenu = "main"
# menu entries
[menu]
[[menu.main]]
identifier = "home"
name = "Home"
title = "Home"
url = "/docs"
weight = 1
[[menu.main]]
identifier = "user"
url = "/docs/user"
name = "User Guides"
title = "User Guides"
weight = 2
[[menu.main]]
identifier = "design"
url = "/docs/design"
name = "Design"
title = "Design"
weight = 5
[[menu.main]]
identifier = "troubleshooting"
url = "/docs/troubleshooting"
name = "Troubleshooting"
title = "Troubleshooting"
weight = 6
[[menu.main]]
identifier = "contributing"
url = "/docs/contributing"
name = "Contributing"
title = "Contributing"
weight = 7

[outputs]
home = ["HTML"]

[params]

# First one is picked as the Twitter card image if not set on page.
# images = ["images/project-illustration.png"]

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo = "https://github.com/aojea/kindnet"

# Specify a value here if your content directory is not in your repo's root directory
github_subdir = "site"

# Uncomment this if your GitHub repo does not have "main" as the default branch,
# or specify a new value if you want to reference another branch in your GitHub links
github_branch= "main"

# Enable Lunr.js offline search
offlineSearch = false

# Enable syntax highlighting and copy buttons on code blocks with Prism
prism_syntax_highlighting = false

[params.copyright]
  authors = "Antonio Ojea | [CC BY 4.0](https://creativecommons.org/licenses/by/4.0) | "
  from_year = 2019

# User interface configuration
[params.ui]
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
# Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top navbar
navbar_logo = false
# Set to true if you don't want the top navbar to be translucent when over a `block/cover`, like on the homepage.
navbar_translucent_over_cover_disable = false
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = false
# Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = false

# Adds a reading time to the top of each doc.
# If you want this feature, but occasionally need to remove the Reading time from a single page,
# add "hide_readingtime: true" to the page's front matter
[params.ui.readingtime]
enable = false

[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.
[[params.links.user]]
  name = "SIG Network mailing list"
  url = "https://groups.google.com/forum/#!forum/kubernetes-sig-network"
  icon = "fa fa-envelope"
  desc = "Discussion and help from your fellow users"
[[params.links.developer]]
  name = "GitHub"
  url = "https://github.com/aojea/kindnet"
  icon = "fab fa-github"
  desc = "Development takes place here!"
[[params.links.developer]]
  name = "Slack"
  url = "https://kubernetes.slack.com/messages/sig-network"
  icon = "fab fa-slack"
  desc = "Chat with other project developers"

[services]
[services.googleAnalytics]
id = "G-TP7BW08VCW"

# privacy settings
[privacy]
[privacy.youtube]
# enable the cookie-less youtube in built-in hugo shortcode
privacyEnhanced = true

[module]
[[module.imports]]
path = 'github.com/google/docsy'