/*
Copyright Antonio Ojea

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	versioned "github.com/aojea/kindnet/apis/clientset/versioned"
	internalinterfaces "github.com/aojea/kindnet/apis/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/aojea/kindnet/apis/listers/config/v1alpha1"
	configv1alpha1 "github.com/aojea/kindnet/pkg/apis/config/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ConfigurationListInformer provides access to a shared informer and lister for
// ConfigurationLists.
type ConfigurationListInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.ConfigurationListLister
}

type configurationListInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewConfigurationListInformer constructs a new informer for ConfigurationList type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewConfigurationListInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredConfigurationListInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredConfigurationListInformer constructs a new informer for ConfigurationList type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredConfigurationListInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KindnetV1alpha1().ConfigurationLists(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KindnetV1alpha1().ConfigurationLists(namespace).Watch(context.TODO(), options)
			},
		},
		&configv1alpha1.ConfigurationList{},
		resyncPeriod,
		indexers,
	)
}

func (f *configurationListInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredConfigurationListInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *configurationListInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&configv1alpha1.ConfigurationList{}, f.defaultInformer)
}

func (f *configurationListInformer) Lister() v1alpha1.ConfigurationListLister {
	return v1alpha1.NewConfigurationListLister(f.Informer().GetIndexer())
}
