name: Test

on: [push, pull_request]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: aojea/kindnetd
permissions: write-all

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.24.x]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v5
    - run: sudo make test
    - run: make verify

